//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.03 at 10:02:57 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tirmizee.com/ws/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tirmizee.ws.user;
