//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.03 at 05:48:33 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tirmizee.com/ws/employees")
package com.tirmizee.ws.employees;
